version: 2

sources:
  - name: spotify
    schema: spotify              # or use {{ target.schema }} for environment-safe naming
    loader: bigquery                 # identifies how data is loaded (fivetran, airbyte, etc.)
    tables:
      - name: charts
        identifier: raw_charts
      - name: music_type
        identifier: raw_spotify_data
models:
 - name: stg_spotify__charts
   description: contient par titre le classement, la date, l'artiste, le pays, le chart, le nb de streams (26 millions de lignes)
   columns: # documentation - il n'est pas nécessaire d'indiquer toutes les colonnes surtout si elles sont bien normées
   - name: title #STR
     tests:
      - not_null
   - name: rank #INT
   - name: date #DATE   
   - name: artist #STR
   - name: url #STR colonne à utiliser pour extraire le track ID
   - name: country #STR 70 pays
   - name: chart #STR viral50 ou top200
   - name: trend #STR
   - name: streams #INT
 - name: stg_spotify__music_type
   description: contient pour chaque titre (track id), l'album, la popularité, la durée, la date de sortie et les indicateurs spotify (danceability...)
   columns: 
   - name: track_id #STR
     tests:
      - not_null
   - name: album #STR
   - name: popularity #INT   
   - name: duration_ms #INT
   - name: explicit #BOOL 1 = explicit, 0 = not explicited ou on ne sait pas
   - name: release_date #STR
   - name: af_danceability #FLOAT
   - name: af_energy #FLOAT
   - name: af_speechiness #FLOAT
   - name: af_acousticness #FLOAT
   - name: af_instrumentalness #FLOAT
   - name: af_valence #FLOAT
   - name: af_tempo #FLOAT
 - name: int_spotify__charts
   description: table intermédiaire qui contient le track id créé à partir de la colonne url
   columns: 
   - name: track_id #STR
 - name: int_spotify__music_type
   description: table intermédiaire clean -> changement au format date et suppression NULL sur album et duration ms a 0
 - name: int_spotify__main_join
   description: table intermédiaire qui fait la jointure entre les tables int_spotify__charts et int_spotify__music_type
   columns: 
   - name: region #STR région du monde pour regrouper les pays